### ISSUE TITLE
Can't bind to IP address upon node launch

### ISSUE THREAD

**Issue by mcavagro** [0xbas3d/HandyHost#2]
Hi, I can successfully install the software and get as far as launching the node, but when I do, I encounter an `Error: listen tcp 107.175.245.76:21564: bind: cannot assign requested address`. This is after the speed test is successfully run, the handshake and VPN service is started, and the node and account are queried. I have run netstat on the TCP port and it is available, not in use. Any ideas what's causing it? Happens upon both external and local installation. Thanks

Edit: Problem fixed by changing to a completely new TCP port.

**Comment by zak04** [comment]
Im seeing this issue now, I tried changing the TCP port but it s still throwing the same error.
I am changing the port conf under config.toml
